name : Main CI
run-name : ${{github.actor}} is running the main CI
on : [push]

jobs :
  setup_dependencies : 
    runs-on : ubuntu-latest
    steps : 
      - uses : actions/checkout@v3
      - uses : ./.github/actions/common-steps

  test_backend : 
    needs : setup_dependencies
    runs-on : ubuntu-latest
    steps : 
      - uses : actions/checkout@v3
      - uses : ./.github/actions/common-steps
      - name : Run backend tests
        run : yarn workspace backend test

  lint_backend : 
    needs : setup_dependencies
    runs-on : ubuntu-latest
    steps : 
      - uses : actions/chechout@v3
      - uses : ./.github/actions/common-steps
      - name : Run backend lint
        run : yarn workspace backend lint:check
      - name : Type check
        run : yarn workspace backend type:check